#!/bin/bash

# make sure everything is running from the right directory
# this way we can use relative paths
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd $DIR


# make sure its being run by root
id | grep "uid=0" > /dev/null
if [ "$?" != 0 ]
then
    echo "Please make sure you are running teahaz as root!"
    exit
fi


# make suer docker is installed
docker --version > /dev/null
if [ "$?" != 0 ]
then
    echo "Please make sure you have docker installed!"
    exit
fi




# function gets the id of the running teahaz instance
ID=""
function get_dID {
    running=$( docker ps)

    ID=$(echo $running | grep  -o ".............teahaz_server")

    ID=$(echo $ID | grep  -o "^............")

    if [ "$ID" == "" ]
    then
        ID=""
    fi

}


# TODO come back to this (stop using cron for something that clearly doesnt need cron)
function run_root_scripts {
    # its in a loop because it will only manage to run once the container is running
    while [ 1 ]
    do
        get_dID

        # if the container is running
        if [ "$ID" != "" ]
        then
            # run root script inside container
            docker exec --user root $ID /home/teahaz/docker/root_deploy.sh
            exit

            # if it fails, run it again
            # if [ "$?" == 0 ]
            # then
            #     exit
            # fi
            # sleep 6
        fi
    done
}



# kill container on ./run kill
if [ "$1" == "kill" ]
then

    get_dID

    if [ "$ID" == "" ]
    then
        echo "no container running"

    else
        docker kill $ID

    fi



# get shell in container on ./run shell
elif [ "$1" == "shell" ]
then

    get_dID

    if [ "$ID" == "" ]
    then
        echo "no container running"

    else
        docker exec -it $ID /bin/bash

    fi




# rebuild container on ./run rebuild
elif [ "$1" == "rebuild" ]
then

    cd $DIR/docker

    docker build --no-cache -t teahaz_server:latest .




# just run the container normally on ./run
else
    get_dID

    # if the server is not running, run it
    if [ "$ID" == "" ]
    then

        cd $DIR/docker

        docker build -t teahaz_server:latest .

        run_root_scripts &

        docker run -p 80:80 -p 443:443 -e PYTHONUNBUFFERED=0 -e TEAHAZ_PORT=13337 --rm -v $DIR:/home/teahaz teahaz_server:latest

    else
        echo "server is already running"
    fi

fi
