#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

ID=""
function get_dID {
    running=$( docker ps)

    ID=$(echo $running | grep  -o ".............teahaz_server")

    ID=$(echo $ID | grep  -o "^............")

    echo $ID

    if [ "$ID" == "" ]
    then
        echo "container not running"
        ID=""

    fi

}


function git_pull {

    cd $DIR

    git pull
    if [ "$?" != 0 ]
    then
        echo "error while getting new updates"
        exit
    fi


}


if [ "$1" == "kill" ]
then

    get_dID

    if [ "$ID" == "" ]
    then
        echo "no container running"

    else
        docker kill $ID

    fi



elif [ "$1" == "shell" ]
then

    get_dID

    if [ "$ID" == "" ]
    then
        echo "no container running"

    else
        docker exec -it $ID /bin/bash

    fi




elif [ "$1" == "rebuild" ]
then

    git_pull

    cd $DIR/docker

    docker build --no-cache -t teahaz_server:latest .


else

    git_pull

    get_dID

    if [ "$ID" == "" ]
    then
        cd $DIR/docker

        docker build -t teahaz_server:latest .

        docker run -p 13337:13337 -e PYTHONUNBUFFERED=0 --rm -v $DIR:/home/teahaz teahaz_server:latest
    else
        echo "server is already running"
    fi

fi
